### ISSUE TITLE
problem using audioTrainTest.featureAndTrain and fileClassification

### ISSUE THREAD

**Issue by lliepert** [tyiannak/pyAudioAnalysis#101]
Hi all,

I am currently trying to use pyAudioAnalysis to segment a song into music and non-music sections.  I used featureAndTrain on a directory of music and nonmusic files to train models for each of svm, svm-rbf, knn, gradient boosting, extra trees, and random forest.  I then split songs into 2 second chunks and ran each of them through fileClassification using the prior models.  However, when I run fileClassifier on certain audio chunks, I receive the following error: 

`ValueError: Input contains NaN, infinity or a value too large for dtype('float64').`

The traceback is

`/opt/pyAudioAnalysis/audioFeatureExtraction.py:69: RuntimeWarning: invalid value encountered in divide
  Xt = Xt / Xt.max()
/opt/pyAudioAnalysis/audioFeatureExtraction.py:285: RuntimeWarning: invalid value encountered in divide
  finalC /= spec.sum()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/pyAudioAnalysis/audioTrainTest.py", line 1015, in fileClassification
    [Result, P] = classifierWrapper(Classifier, modelType, curFV)    # classification        
  File "/opt/pyAudioAnalysis/audioTrainTest.py", line 79, in classifierWrapper
    R = classifier.predict(testSample.reshape(1,-1))[0]
  File "/home/x/.local/lib/python2.7/site-packages/sklearn/svm/base.py", line 573, in predict
    y = super(BaseSVC, self).predict(X)
  File "/home/x/.local/lib/python2.7/site-packages/sklearn/svm/base.py", line 310, in predict
    X = self._validate_for_predict(X)
  File "/home/x/.local/lib/python2.7/site-packages/sklearn/svm/base.py", line 459, in _validate_for_predict
    X = check_array(X, accept_sparse='csr', dtype=np.float64, order="C")
  File "/home/x/.local/lib/python2.7/site-packages/sklearn/utils/validation.py", line 407, in check_array
    _assert_all_finite(array)
  File "/home/x/.local/lib/python2.7/site-packages/sklearn/utils/validation.py", line 58, in _assert_all_finite
    " or a value too large for %r." % X.dtype)
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
`

On a test of approximately 20,000 song chunks, I received the error 390 times each for svm, svm-rbf, extra trees, gradient boosting, and random forest.  I received the error 0 times on knn.  The errors were not always on the same files.  
I trained the models on a dataset of 100 songs, split into approximately 500 segments.
I updated pyAudioAnalysis earlier this week and am running on commit `fedbf7747ad517b58adcb62c2bcfcd6c2147b6cd`.  

Has anyone seen this error before?  Thank you!

**Comment by tyiannak** [comment]
Thank you for your comment.
Would it be possible to share a couple of audio samples for which the problem appears?

**Comment by bkrzyzanski** [comment]
I'm experiencing similar issue. Library is crashing while processing wav file containing nothing but a few seconds of silence.

**Comment by miller2j** [comment]
@tyiannak is this problem addressed or are you still awaiting some sample audio samples?
As I have recently come across this issue as well
