### ISSUE TITLE
installation on win 10. magic.h is missing

### ISSUE THREAD

**Issue by YitzhakSp** [tyiannak/pyAudioAnalysis#109]
I installed the library in win 10. I installed the libmagic dependency by:
```
pip install python-libmagic
```
when I run

```
from pyAudioAnalysis import audioTrainTest 
```

I get the following error

```
C:\Users\Yitzhak\Anaconda3\python.exe C:/Users/Yitzhak/Projects/gameslearning/main3.py
_cffi__xa0d5132dx54cebdac.c
LINK : fatal error LNK1181: cannot open input file 'magic.lib'
Traceback (most recent call last):
  File "C:\Users\Yitzhak\Anaconda3\lib\distutils\_msvccompiler.py", line 478, in link
    self.spawn([self.linker] + ld_args)
  File "C:\Users\Yitzhak\Anaconda3\lib\distutils\_msvccompiler.py", line 501, in spawn
    return super().spawn(cmd)
  File "C:\Users\Yitzhak\Anaconda3\lib\distutils\ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "C:\Users\Yitzhak\Anaconda3\lib\distutils\spawn.py", line 38, in spawn
    _spawn_nt(cmd, search_path, dry_run=dry_run)
  File "C:\Users\Yitzhak\Anaconda3\lib\distutils\spawn.py", line 81, in _spawn_nt
    "command %r failed with exit status %d" % (cmd, rc))
distutils.errors.DistutilsExecError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1181
```
Multiple attempts to fix this issue already failed .was anyone able to run pyAudioAnalysis on win 10 ?

**Comment by buaatianye** [comment]
I encountered a similiar problem when I run pyAudioAnalysis on win 10, cannot find libmagic, but I have installed python-libmagic. For your problem, I think you can install visual studio 2015.

**Comment by VladLimbean** [comment]
I installed Visual C++ for Python.

I'm getting this error:
```File "C:\\cffi\ffiplatform.py", line 62, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.ffiplatform.VerificationError: CompileError: command 'C:\\Users\\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\cl.exe' failed with exit status 2```

Any ideas?

**Comment by Githeo** [comment]
Exactly same error here as Vlad, but on Mac 10.12.

**Comment by sanny1** [comment]
I think you have to download libmagic for c++ as well

**Comment by VictorGaiva** [comment]
I'll try to replicate the error.

**Comment by VladLimbean** [comment]
I bypassed the issue by moving to Ubuntu. I'm still interested in how to fix it for Windows

**Comment by RasimusM** [comment]
Just to express that this is still existing problem. My situation is Win 10, Python VirtualEnv, ImageMagick installation, pip install libmagic, import magic --> magic.h can't be found.

Should cl.exe be supplied with include path from registry / %PATH% (either doesn't seem to contain any magick or python virtualenv include-folders)? Should magic.h be in virtual environment's include-folder (copying file there won't help, though), or should cffi detect it from ImageMagick's installation folder (which is probably against virtualenv's philosophy...), or something?

**Comment by francesco1119** [comment]
yep, this problem is still present on Windows 10

**Comment by RasimusM** [comment]
Update: as mentioned by francesco1119 in above mentioned referenced message thread, this helped me:
- Reinstall libmagic using pip
- Download and install (with pip install -r <file name and path>) Windows-specific whl-file from https://pypi.python.org/pypi/python-magic-bin/0.4.14

**Comment by francesco1119** [comment]
Yep, installing `python_magic_bin-0.4.14-py2.py3-none-win32.whl `made the trick.
Thank you

**Comment by viveksj** [comment]
installing python_magic_bin-0.4.14-py2.py3-none-win_amd64.whl did the trick. But, here's the kicker.
I use Intel and not AMD.
(It does give me a RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work.  Warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning))
But, I'll figure that out.

**Comment by channae** [comment]
@viveksj I'm facing the same issue in High Sierra Mac. How did you resolve the FFMPEG issue?

**Comment by francesco1119** [comment]
Hi @viveksj and @channae ,
the message says **"...may not work"**. 
Have you checked if it works or not?

**Comment by channae** [comment]
@francesco1119 It didn't work so I installed ffmpeg using brew. 

```
$ brew install ffmpeg --force
$ brew link ffmpeg
```

Now the issue is resolved. Thanks
