### ISSUE TITLE
Can't install scikits.talkbox

### ISSUE THREAD

**Issue by Neo0** [tyiannak/pyAudioAnalysis#14]
I met a issue, when I install scikits.talkbox.
ubuntu 14.04 LTS
python 2.7.6

Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/scikits.talkbox/setup.py", line 10, in <module>
        from numpy.distutils.core import setup
    ImportError: No module named 'numpy'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/scikits.talkbox/setup.py", line 10, in <module>

    from numpy.distutils.core import setup

ImportError: No module named 'numpy'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/scikits.talkbox
Storing debug log for failure in /home/****/.pip/pip.log

And my numpy install success.I can import numpy and  from numpy.distutils.core import setup.

**Comment by giovana-morais** [comment]
does anybody know a solution to this problem yet? everytime i have to install it, i face the same problem. 😞
