### ISSUE TITLE
speakerDiarization method from audioAnalysis.py returning TypeError:'NoneType'object is not iterable

### ISSUE THREAD

**Issue by iazzari** [tyiannak/pyAudioAnalysis#145]
Hello, I'm trying to use this module to separate two speakers in a wav audio file and tried to run it as explained on the wiki:
`python audioanalysis.py speakerDiarization -i teste.wav --num 2`

but I'm getting the following error
```
Traceback (most recent call last):
  File "audioAnalysis.py", line 466, in <module>
    speakerDiarizationWrapper(args.input, args.num, args.flsd)
  File "audioAnalysis.py", line 230, in speakerDiarizationWrapper
    aS.speakerDiarization(inputFile, numSpeakers, LDAdim=0, PLOT=True)
  File "/Users/ivanazzari/anaconda/lib/python2.7/site-packages/pyAudioAnalysis/audioSegmentation.py", line 703, in speakerDiarization
    [Classifier1, MEAN1, STD1, classNames1, mtWin1, mtStep1, stWin1, stStep1, computeBEAT1] = aT.loadKNNModel(os.path.join("data","knnSpeakerAll"))
TypeError: 'NoneType' object is not iterable

```

**Comment by McKnightRider** [comment]
I got this error as well when I ran the speakerDiarization() function on a file in my folder (what you call teste.wav).  I eventually sorted it out by copying the full pyAudioAnalysis/data folder into the same folder as teste.wav, which works as "aT.loadKNNModel(os.path.join("data","knnSpeakerAll"))" is looking in the data folder for the file knnSpeakerAll.
