### ISSUE TITLE
speakerDiarization method from audioAnalysis.py returning wrong array 

### ISSUE THREAD

**Issue by iazzari** [tyiannak/pyAudioAnalysis#147]
I run speaker diarization and it returns
"
array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        1.,  1.,  1.,  1.,  1.,  1. ...])
"
my program is 
"
import pyAudioAnalysis.audioSegmentation as aS
cls = aS.speakerDiarization("/Users/ivanazzari/Google Drive/speech_test/teste_bruno.wav",2, mtSize=2.0, mtStep=0.2, stWin=0.05, LDAdim=35, PLOT=False)
cls
"

and I would like it to return the seconds for later I cut them

**Comment by Rasipuram** [comment]
Hi, 

Were you able to resolve the diarization issue? 

If I run your code, I get an error like this. I infact followed the comment that McKnightRider made in this link
https://github.com/tyiannak/pyAudioAnalysis/issues/145
*************
Traceback (most recent call last):
  File "exDia.py", line 2, in <module>
    cls = aS.speakerDiarization("/Users/sowmyar/Desktop/eguruStartUp/sampleAudioWav.wav", 2, mtSize=2.0, mtStep=0.2, stWin=0.05, LDAdim=35, PLOT=False )
  File "/Users/sowmyar/Downloads/first-impressions-master/data/pyAudioAnalysis/audioSegmentation.py", line 703, in speakerDiarization
    [Classifier1, MEAN1, STD1, classNames1, mtWin1, mtStep1, stWin1, stStep1, computeBEAT1] = aT.loadKNNModel(os.path.join("data","knnSpeakerAll"))
TypeError: 'NoneType' object is not iterable
*************8
Running the command line version according to wiki, generates only a graph with specified number of speakers. Is there any way to generate a separate wav file for every speaker?
python audioAnalysis.py speakerDiarization -i data/diarizationExample.wav --num 2

**Comment by JPery** [comment]
Your mtStep is 0.2, so the returned array is classified every 0.2 seconds. Every 0 or 1 means 0.2 seconds of your audio.

**Comment by manad-mishra** [comment]
Set LDAdim=0, in the command line implementation that's what it is set to.

**Comment by raghavk92** [comment]
@Rasipuram As you wrote 

> Running the command line version according to wiki, generates only a graph with specified number of speakers

Where is this graph generated and saved . I am using mobaxterm and running the command on remote server but i only get a deprecated waring and  then program ends.

My output is 
```
python audioAnalysis.py speakerDiarization -i data/_carl_3_1_16k.wav --num 2
/home/ubuntu/anaconda3/lib/python3.6/site-packages/matplotlib/__init__.py:1067: UserWarning: Duplicate key in file "/home/ubuntu/.config/matplotlib/matplotlibrc", line #2
  (fname, cnt))
/home/ubuntu/anaconda3/lib/python3.6/site-packages/matplotlib/__init__.py:1067: UserWarning: Duplicate key in file "/home/ubuntu/.config/matplotlib/matplotlibrc", line #3
  (fname, cnt))
/home/ubuntu/anaconda3/lib/python3.6/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d
```
