### ISSUE TITLE
SKLearn ValueError: The number of classes has to be greater than one; got 1 while running audioTrainTest

### ISSUE THREAD

**Issue by viveksj** [tyiannak/pyAudioAnalysis#149]
I was trying to follow some basic instructions by http://rwx.io/blog/2016/04/08/bp-pyaudioanalysis/
But, I keep on running into the error after analyzing the calls:
Analyzing file 4 of 4: data/training_data/1/11648004178-out.wav

Feature extraction complexity ratio: 12.0 x realtime
Param = 0.00100 - Classifier Evaluation Experiment 1 of 100
/usr/lib/python2.7/dist-packages/sklearn/svm/base.py:514: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y_ = column_or_1d(y, warn=True)
Traceback (most recent call last):
  File "createClassifierModel.py", line 18, in <module>
    aT.featureAndTrain(subdirectories, 1.0, 1.0, aT.shortTermWindow, aT.shortTermStep, "svm", "svmModel", False)
  File "/home/test_env/pyAudioAnalysis/audioTrainTest.py", line 329, in featureAndTrain
    bestParam = evaluateClassifier(features, classNames, 100, classifierType, classifierParams, 0, perTrain)
  File "/home/test_env/pyAudioAnalysis/audioTrainTest.py", line 718, in evaluateClassifier
    Classifier = trainSVM(featuresTrain, C)
  File "/home/test_env/pyAudioAnalysis/audioTrainTest.py", line 160, in trainSVM
    svm.fit(X,Y)
  File "/usr/lib/python2.7/dist-packages/sklearn/svm/base.py", line 151, in fit
    y = self._validate_targets(y)
  File "/usr/lib/python2.7/dist-packages/sklearn/svm/base.py", line 521, in _validate_targets
    % len(cls))
ValueError: The number of classes has to be greater than one; got 1
root@ip-10-102-1-142:/home/test_env

**Comment by stephenn102** [comment]
How did you fix this error?
