### ISSUE TITLE
Segmentation numpy issue

### ISSUE THREAD

**Issue by viveksj** [tyiannak/pyAudioAnalysis#151]
When I run the python command,
[flagsInd, classesAll, acc, CM] = aS.mtFileClassification("sample.wav", "svmv_st", "svm", True)

I get TypeError: only size-1 arrays can be converted to Python scalars for the line:
 File "pyAudioAnalysis\audioSegmentation.py", line 220, in plotSegmentationResults
    ax2.bar(numpy.array(range(len(classNames))) + 0.5, Percentages)

How do I fix it? The syntax looks right to me?

Entire Traceback:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyAudioAnalysis\audioSegmentation.py", line 546, in mtFileClassification
    acc = plotSegmentationResults(flagsInd, flagsIndGT, classNames, mtStep, not plotResults)
  File "pyAudioAnalysis\audioSegmentation.py", line 220, in plotSegmentationResults
    ax2.bar(numpy.array(range(len(classNames))) + 0.5, Percentages)
  File "C:\Users\Vivek\Anaconda3\envs\py2\lib\site-packages\matplotlib\__init__.py", line 1717, in inner
    return func(ax, *args, **kwargs)
  File "C:\Users\Vivek\Anaconda3\envs\py2\lib\site-packages\matplotlib\axes\_axes.py", line 2087, in bar
    label='_nolegend_',
  File "C:\Users\Vivek\Anaconda3\envs\py2\lib\site-packages\matplotlib\patches.py", line 659, in __init__
    Patch.__init__(self, **kwargs)
  File "C:\Users\Vivek\Anaconda3\envs\py2\lib\site-packages\matplotlib\patches.py", line 103, in __init__
    self.set_linewidth(linewidth)
  File "C:\Users\Vivek\Anaconda3\envs\py2\lib\site-packages\matplotlib\patches.py", line 351, in set_linewidth
    self._linewidth = float(w)
TypeError: only size-1 arrays can be converted to Python scalars

**Comment by williancomp** [comment]
Uninstall matplotlib:

`pip uninstall matplotlib`

and then install version 1.5.3

`pip install matplotlib==1.5.3`

**Comment by awani216** [comment]
The problem persists with v2.2 also.

**Comment by chuckienorton** [comment]
FYI for future readers williancomp's suggestion works (not ideal but fine for a closed environment).
