### ISSUE TITLE
ValueError: cannot reshape array of size 4800 into shape (240,10)

### ISSUE THREAD

**Issue by scut-salmon** [tyiannak/pyAudioAnalysis#162]
Hello, 
The code didn't work when I using 
 F = audioFeatureExtraction.stFeatureExtraction(x, Fs, 0.050*Fs, 0.025*Fs);
which says 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyAudioAnalysis/audioFeatureExtraction.py", line 577, in stFeatureExtraction
    curFV[2] = stEnergyEntropy(x)                    # short-term entropy of energy
  File "pyAudioAnalysis/audioFeatureExtraction.py", line 51, in stEnergyEntropy
    subWindows = frame.reshape(subWinLength, numOfShortBlocks, order='F').copy()
ValueError: cannot reshape array of size 4800 into shape (240,10)

Could you give me any suggestion to solve it? Thanks for your time.

**Comment by scut-salmon** [comment]
The code works when I use 
F = audioFeatureExtraction.stFeatureExtraction(x[:, 0], Fs, 0.050Fs, 0.025Fs)

It seems that the audio with two channels is not work. What should I do, any examples for this kind of audio?

Thanks

**Comment by pvanlaar** [comment]
These functions are designed for single channel audio signals. I am not sure if extracting a feature for multiple channels does even exist. You can merge the audio first, by for example averaging the channels or extract the features for each channel. It depends on the meaning of the channels. That is if they are captured by multiple microphones for example.

**Comment by AakashMallik** [comment]
Yup. Apparently taking the mean of the two channels works. @scut-salmon

**Comment by zhengqun** [comment]
you can use two channels   .wav file

**Comment by burak43** [comment]
audioBasicIO.stereo_to_mono(signal) does the averaging. See https://github.com/tyiannak/pyAudioAnalysis/blob/master/pyAudioAnalysis/MidTermFeatures.py#L328-L329
