### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/np/bm64l_3d2xl07vpkpl9f2sv80000gn/T/pip-build-FFdram/audiotools/

### ISSUE THREAD

**Issue by arshiyak9** [tyiannak/pyAudioAnalysis#168]
Collecting audiotools
  Using cached https://files.pythonhosted.org/packages/a9/14/5ef88704f5c662ee79ce2beaf92270f44b494a5234dcff4d0bac438855f0/audiotools-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/np/bm64l_3d2xl07vpkpl9f2sv80000gn/T/pip-build-FFdram/audiotools/setup.py", line 7, in <module>
        with open(path.join(here, 'README.md'), encoding='utf-8') as f:
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py", line 898, in open
        file = __builtin__.open(filename, mode, buffering)
    IOError: [Errno 2] No such file or directory: '/private/var/folders/np/bm64l_3d2xl07vpkpl9f2sv80000gn/T/pip-build-FFdram/audiotools/README.md'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/np/bm64l_3d2xl07vpkpl9f2sv80000gn/T/pip-build-FFdram/audiotools/

**Comment by jonorthwash** [comment]
I can also confirm that this is an issue with version 0.1.0, and it's interfering with pip installation of audiotools as well.  The solution seems to be to either `touch README.md` or get version 3.

**Comment by tonko22** [comment]
Similar issue here, on Python 3.7:
$ pip install audiotools
Collecting audiotools
  Using cached https://files.pythonhosted.org/packages/a9/14/5ef88704f5c662ee79ce2beaf92270f44b494a5234dcff4d0bac438855f0/audiotools-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-0xt8jpq5/audiotools/setup.py", line 7, in <module>
        with open(path.join(here, 'README.md'), encoding='utf-8') as f:
      File "/home/tonko22/.virtualenvs/py37/lib/python3.7/codecs.py", line 898, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-0xt8jpq5/audiotools/README.md'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-0xt8jpq5/audiotools/

**Comment by jonorthwash** [comment]
I should clarify: by "version 3", I meant audiotools, not python.  It's available here:
http://audiotools.sourceforge.net

**Comment by DeLaRiva** [comment]
I face the same issue

**Comment by SevRyb** [comment]
I too have the same issue.
