### ISSUE TITLE
pyAudioAnalysis Error

### ISSUE THREAD

**Issue by thaingiW** [tyiannak/pyAudioAnalysis#176]
python /home/lwin/speech-emotion/Speech_emotion_recognition_BLSTM-master1/find_best_model.py -d "berlin" -p /"home/lwin/speech-emotion/Speech_emotion_recognition_BLSTM-master1/wav" -l -e -c 7
Using TensorFlow backend.
Writing berlin data set to file...
Traceback (most recent call last):
  File "/home/lwin/speech-emotion/Speech_emotion_recognition_BLSTM-master1/find_best_model.py", line 163, in <module>
    functions.feature_extract(ds.data, nb_samples=len(ds.targets), dataset=dataset)
  File "/home/lwin/speech-emotion/Speech_emotion_recognition_BLSTM-master1/utility/functions.py", line 20, in feature_extract
    hr_pitch = audioFeatureExtraction.stFeatureSpeed(x, Fs, globalvars.frame_size * Fs, globalvars.step * Fs)
  File "/usr/local/lib/python3.5/dist-packages/pyAudioAnalysis/audioFeatureExtraction.py", line 679, in stFeatureSpeed
    [fbank, freqs] = mfccInitFilterBanks(Fs, nfft, lowfreq, linsc, logsc, nlinfil, nlogfil)
  File "/usr/local/lib/python3.5/dist-packages/pyAudioAnalysis/audioFeatureExtraction.py", line 210, in mfccInitFilterBanks
    fbank = numpy.zeros((nFiltTotal, nfft))
TypeError: 'float' object cannot be interpreted as an integer

**Comment by pvanlaar** [comment]
A quick fix might be to replace `nfft = Win / 2` on line 663 of audioFeatureExtraction.py 
with `nfft = int(Win / 2)`

**Comment by thaingiW** [comment]
Thank you very much!
