### ISSUE TITLE
UnboundLocalError

### ISSUE THREAD

**Issue by YK9999** [tyiannak/pyAudioAnalysis#189]
While training the module got this error. I have installed latest version and all tried with python2.7 and python3, got same error in both cases
from pyAudioAnalysis import audioTrainTest as aT
aT.featureAndTrain(<file/dir>, 1.0, 1.0, aT.shortTermWindow, aT.shortTermStep, "svm", "svmModel", False)

Error :
local variable 'mt_feature_names' referenced before assignment

**Comment by tyiannak** [comment]
You've probably provided a path with no audio files in dirWavFeatureExtraction(). I've added a minor modification on the latest version to return empty list in that case

**Comment by YK9999** [comment]
is there any method o test music/speech separation script without training

**Comment by YK9999** [comment]
aT.fileClassification("pyAudioAnalysis/data/doremi.wav", "pyAudioAnalysis/data/svmSM","svmSM")
  File "~/pyAudioAnalysis/pyAudioAnalysis/audioTrainTest.py", line 913, in fileClassification
    compute_beat] = load_model(model_name)
  File "~/pyAudioAnalysis/pyAudioAnalysis/audioTrainTest.py", line 580, in load_model
    MEAN = numpy.array(MEAN)

after adding classifier as svmSMMEANS there is new error 

Traceback (most recent call last):
  File "testing.py", line 3, in <module>
    **aT.fileClassification("pyAudioAnalysis/data/doremi.wav","pyAudioAnalysis/data/svmSMMEANS","svmSM")**
  File "~/pyAudioAnalysis/pyAudioAnalysis/audioTrainTest.py", line 913, in fileClassification
    compute_beat] = load_model(model_name)
  File "~/pyAudioAnalysis/pyAudioAnalysis/audioTrainTest.py", line 561, in load_model
    except IOerror:
NameError: global name 'IOerror' is not defined

**Comment by TeeManiac** [comment]
@YK9999  Did you resolve this issue? I am also getting same error. Please help.
 File "/usr/local/lib/python3.6/dist-packages/pyAudioAnalysis/audioTrainTest.py", line 520, in load_model_knn
    except IOerror:
NameError: name 'IOerror' is not defined
