### ISSUE TITLE
Diarization Example fails with UnboundLocalError: local variable 'MEAN' referenced before assignment

### ISSUE THREAD

**Issue by Joboman555** [tyiannak/pyAudioAnalysis#199]
I am trying to run the unsupervised segmentation example explained [here](https://github.com/tyiannak/pyAudioAnalysis/wiki/5.-Segmentation). 

I am running the following command:

`python audioAnalysis.py segmentClassifyFile -i data/scottish.wav
`

I get the following error:

![image](https://user-images.githubusercontent.com/14250739/47245381-03c51380-d3c7-11e8-8e00-012d9175973d.png)

<details>
<summary> Plaintext Error </summary>

`Traceback (most recent call last):
  File "audioAnalysis.py", line 586, in <module>
    segmentclassifyFileWrapper(args.input, args.modelName, args.model)
  File "audioAnalysis.py", line 203, in segmentclassifyFileWrapper
    aS.mtFileClassification(inputWavFile, model_name, model_type, True, gtFile)
  File "/home/jspear/Development/diarization/pyAudioAnalysis/pyAudioAnalysis/audioSegmentation.py", line 519, in mtFileClassification
    compute_beat] = aT.load_model(model_name)
  File "/home/jspear/Development/diarization/pyAudioAnalysis/pyAudioAnalysis/audioTrainTest.py", line 580, in load_model
    MEAN = numpy.array(MEAN)
UnboundLocalError: local variable 'MEAN' referenced before assignment`
</details>

I am using Python 2.7, running the latest version of the code as of 2018-October-19th (commit cee48de0df)

Any help would be appreciated.

**Comment by tyiannak** [comment]
Thank you for your comment. It seems that this is due to the fact that the model used in this function has been trained in python 3. Have you tried running the code in python 3?

**Comment by Joboman555** [comment]
When I run with python 3.5.2 I get the following error:

![image](https://user-images.githubusercontent.com/14250739/47257426-98795100-d45b-11e8-8868-d638f59e37a9.png)

<details>
  <summary>Plaintext</summary>
  
`Traceback (most recent call last):
  File "audioAnalysis.py", line 9, in <module>
    from pyAudioAnalysis import audioSegmentation as aS
  File "/home/jspear/Development/diarization/pyAudioAnalysis/pyAudioAnalysis/audioSegmentation.py", line 16, in <module>
    import hmmlearn.hmm
  File "/home/jspear/.virtualenvs/diarization3/lib/python3.5/site-packages/hmmlearn/hmm.py", line 20, in <module>
    from .base import _BaseHMM
  File "/home/jspear/.virtualenvs/diarization3/lib/python3.5/site-packages/hmmlearn/base.py", line 13, in <module>
    from . import _hmmc
ImportError: /home/jspear/.virtualenvs/diarization3/lib/python3.5/site-packages/hmmlearn/_hmmc.cpython-35m-x86_64-linux-gnu.so: undefined symbol: npy_fabsl`

</details>

**Comment by Joboman555** [comment]
@tyiannak Does running this command work for you? If so, could you provide which version of python you are using as well as the output of running pip freeze? 

I believe this may be a package versioning issue.

**Comment by leoxagy12** [comment]
Hi. 
I am having the same issue.
![imagen](https://user-images.githubusercontent.com/1550174/47936814-4a316c80-deb5-11e8-9e49-9c02cf751601.png)

**Comment by zhengqun** [comment]
I have the same issue 'MEAN'.

**Comment by diogomoreira** [comment]
Same here, but the message is `UnboundLocalError: local variable 'STD' referenced before assignment
`
