### ISSUE TITLE
pip install fails with missing readme

### ISSUE THREAD

**Issue by TheLastDestroyer** [tyiannak/pyAudioAnalysis#207]
When trying to install with pip the install fails due to README.md not being present:

```
Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/data/data/com.termux/files/usr/tmp/pip-install-pf9rnn84/audiotools/setup.py", line 7, in <module>
        with open(path.join(here, 'README.md'), encoding='utf-8') as f:
      File "/data/data/com.termux/files/usr/lib/python3.7/codecs.py", line 898, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '/data/data/com.termux/files/usr/tmp/pip-install-pf9rnn84/audiotools/README.md'
```

Downloading source from https://pypi.org/project/audiotools leads to the same error, and the README is missing. Creating an empty readme seems to work

```
$ touch README.md
$ python setup.py egg_info
running egg_info
writing audiotools.egg-info/PKG-INFO
writing dependency_links to audiotools.egg-info/dependency_links.txt
writing requirements to audiotools.egg-info/requires.txt
writing top-level names to audiotools.egg-info/top_level.txt
reading manifest file 'audiotools.egg-info/SOURCES.txt'
writing manifest file 'audiotools.egg-info/SOURCES.txt'
```

**Comment by TheLastDestroyer** [comment]
Turns out pypi has the wrong repo,
