### ISSUE TITLE
MemoryError during speakerDiarization

### ISSUE THREAD

**Issue by qbolec** [tyiannak/pyAudioAnalysis#21]
```
$ python audioAnalysis.py speakerDiarization -i ~/sounds/0F21C41C69FFD804C1257C7F0041617C.wav --num 0 | tee sp.log
Traceback (most recent call last):
  File "audioAnalysis.py", line 465, in <module>
    speakerDiarizationWrapper(args.input, args.num, args.flsd)
  File "audioAnalysis.py", line 229, in speakerDiarizationWrapper
    aS.speakerDiarization(inputFile, numSpeakers, LDAdim=0, PLOT=True)
  File "/[--REDACTED--]/audioSegmentation.py", line 685, in speakerDiarization
    DistancesAll = numpy.sum(distance.squareform(distance.pdist(MidTermFeaturesNorm.T)), axis=0)
  File "/usr/lib/python2.7/dist-packages/scipy/spatial/distance.py", line 1457, in squareform
    M = np.zeros((d, d), dtype=np.double)
MemoryError
```

The wave file is about 4300 seconds long. The program was running for several minutes at least before crash.

**Comment by qbolec** [comment]
I run it again with monitoring in the form of `for((;;));do ps aux | grep '[p]yth';sleep 5;done`
and this is the tail:
```
REDACTED+ 22887 99.7 19.7 1231396 797716 pts/6  Rl+  15:42  23:36 python audioAnalysis.py speakerDiarization -i /home/REDACTED/sounds/0F21C41C69FFD804C1257C7F0041617C.wav --num 0
REDACTED+ 22887 99.7  6.0 654452 246804 pts/6   Rl+  15:42  23:41 python audioAnalysis.py speakerDiarization -i /home/REDACTED/sounds/0F21C41C69FFD804C1257C7F0041617C.wav --num 0
REDACTED+ 22887 99.7  6.4 668340 260796 pts/6   Rl+  15:42  23:46 python audioAnalysis.py speakerDiarization -i /home/REDACTED/sounds/0F21C41C69FFD804C1257C7F0041617C.wav --num 0
REDACTED+ 22887 99.7  6.7 681880 274524 pts/6   Rl+  15:42  23:51 python audioAnalysis.py speakerDiarization -i /home/REDACTED/sounds/0F21C41C69FFD804C1257C7F0041617C.wav --num 0
REDACTED+ 22887 99.7  7.1 696072 288516 pts/6   Rl+  15:42  23:56 python audioAnalysis.py speakerDiarization -i /home/REDACTED/sounds/0F21C41C69FFD804C1257C7F0041617C.wav --num 0
REDACTED+ 22887 99.7  7.6 717004 309364 pts/6   Rl+  15:42  24:01 python audioAnalysis.py speakerDiarization -i /home/REDACTED/sounds/0F21C41C69FFD804C1257C7F0041617C.wav --num 0
REDACTED+ 22887 99.7  7.6 717004 309364 pts/6   Rl+  15:42  24:06 python audioAnalysis.py speakerDiarization -i /home/REDACTED/sounds/0F21C41C69FFD804C1257C7F0041617C.wav --num 0
REDACTED+ 22887 99.7 29.9 2522924 1211188 pts/6 Rl+  15:42  24:11 python audioAnalysis.py speakerDiarization -i /home/REDACTED/sounds/0F21C41C69FFD804C1257C7F0041617C.wav --num 0
```

**Comment by qbolec** [comment]
It seems like the following implementation, could be used instead:
```
def getAllDistances(M):
    sums = numpy.zeros(M.T.shape[0]);
    for i in range(M.T.shape[0]):
       sums[i]= numpy.sum(numpy.linalg.norm(M.T-M.T[i],axis=1))
    return sums;
```

**Comment by tyiannak** [comment]
Thank you. Your file is >1 hour long. I would break it into smaller segments (e.g. 1000 seconds) to avoid memory problems.

**Comment by cappelll** [comment]
Hi. I was experiencing the same problem. qbolec's changed fized for me.
