### ISSUE TITLE
audioTrainTest file calling

### ISSUE THREAD

**Issue by rakky18** [tyiannak/pyAudioAnalysis#222]
I have tried the speaker diarization process. On the function load_mode_knn(), I get an error on the calling of file. 
`
            [Classifier1, MEAN1, STD1, classNames1, mtWin1, mtStep1, stWin1, stStep1, computeBEAT1] = aT.load_model_knn(
                os.path.join(os.path.dirname(os.path.realpath(__file__)), "data", "knnSpeakerAll"))
            [Classifier2, MEAN2, STD2, classNames2, mtWin2, mtStep2, stWin2, stStep2, computeBEAT2] = aT.load_model_knn(
                os.path.join(os.path.dirname(os.path.realpath(__file__)), "data", "knnSpeakerFemaleMale"))`

The error says:

> 
Traceback (most recent call last):
  File "C:/Users/Patrick/PycharmProjects/tangina/Thesis/pyqt.py", line 107, in <lambda>
    speakerDia.triggered.connect(lambda: self.speakerDiarization(self.fileName, self.n_speakers))
  File "C:/Users/Patrick/PycharmProjects/tangina/Thesis/pyqt.py", line 1254, in speakerDiarization
    os.path.join(os.path.dirname(os.path.realpath(__file__)), "data", "knnSpeakerAll"))
TypeError: 'NoneType' object is not iterable

I have tried replacing the line os.path.join(os.path.dirname(os.path.realpath(__file__)) with just my filename passed on the function with it's full path included but it didn't work.

**Comment by rakky18** [comment]
Im not quite sure what's the needed data on the first parameter, i tried printing the os.path.join(os.path.dirname(os.path.realpath(file)) and it showed the path of my C:\Users\Patrick\PyCharmProjects\tangina\Thesis
didn't find file.

It also said didn't find a file, I wont why it needs the path of my project??? I'm confused what is exactly needed.

**Comment by rakky18** [comment]
Fixed it by copying the knnSpeakerAll and knnSpeakerFemaleMale models files to my project path and removing the "data" on the os.path.join.
