### ISSUE TITLE
Result, P, classNames returning (-1,-1,-1)

### ISSUE THREAD

**Issue by vansydy** [tyiannak/pyAudioAnalysis#228]
Training worked perfectly, and the results from training evaluation were perfect. When trying to classify a single file or folder I receive type errors (receiving integer, expecting list for enumerate) upon further debugging I discovered the cause is 

> Result, P, classNames

are all being returned as -1, with no error message. I even went as far as adding additional console logs to audioTrainTest, but still receiving no reason for the return of -1. 

Audio clips are less than 1 second long, WAV format, 8000Hhz Sample Rate. They trained fine, and the directories are being read fine. Same error on both Linux and Windows.

**Comment by vansydy** [comment]
(-1, -1, -1)
Class   Probability
Traceback (most recent call last):
  File "audioAnalysis.py", line 578, in <module>
    classifyFileWrapper(args.input, args.model, args.classifier)
  File "audioAnalysis.py", line 107, in classifyFileWrapper
    for i, c in enumerate(classNames):
TypeError: 'int' object is not iterable

**Comment by paddygoat** [comment]
I got the same (-1, -1, -1) output. Any thoughts?

**Comment by paddygoat** [comment]
if isinstance(x, int):                                 # audio file IO problem
        return (-1, -1, -1)
    if x.shape[0] / float(Fs) <= mt_win:
        return (-1, -1, -1)

My audio file was too short.
