### ISSUE TITLE
Error: cannot reshape array of size 4800 into shape (240,10)

### ISSUE THREAD

**Issue by vybhav72954** [tyiannak/pyAudioAnalysis#281]
```
from pyAudioAnalysis import audioBasicIO
from pyAudioAnalysis import ShortTermFeatures
import matplotlib.pyplot as plt
[Fs, x] = audioBasicIO.read_audio_file("C:/Users/asus/Desktop/Song_Test/Split/Done1.wav")
F, f_names = ShortTermFeatures.feature_extraction(x, Fs, 0.050*Fs, 0.025*Fs)
plt.subplot(2,1,1)
plt.plot(F[0,:])
plt.xlabel('Frame no')
plt.ylabel(f_names[0])
plt.subplot(2,1,2)
plt.plot(F[1,:])
plt.xlabel('Frame no')
plt.ylabel(f_names[1])
plt.show()
```
Results in following error

```
Traceback (most recent call last):
  File "C:/Users/asus/PycharmProjects/untitled/pyaudioanalysis.py", line 5, in <module>
    F, f_names = ShortTermFeatures.feature_extraction(x, Fs, 0.050*Fs, 0.025*Fs)
  File "C:\Users\asus\anaconda3\envs\untitled\lib\site-packages\pyAudioAnalysis\ShortTermFeatures.py", line 629, in feature_extraction
    feature_vector[2] = energy_entropy(x)
  File "C:\Users\asus\anaconda3\envs\untitled\lib\site-packages\pyAudioAnalysis\ShortTermFeatures.py", line 34, in energy_entropy
    sub_wins = frame.reshape(sub_win_len, n_short_blocks, order='F').copy()
ValueError: cannot reshape array of size 4800 into shape (240,10)
```
Kindly suggest the reason and any possible solution.

**Comment by slowglow** [comment]
Most probably your audio file is in stereo. When calling from the command line, the wrapper functions deal with the stereo-to-mono conversion, but when calling the feature extraction functions directly, you have to take care of this yourself. 

Let us know if this solved your problem.
