### ISSUE TITLE
IndexError: index -1 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by 20richardh** [tyiannak/pyAudioAnalysis#294]
I am attempting to run the following command in order to train the HMM on audio segments. I tried the sample code 
          **python audioAnalysis.py trainHMMsegmenter_fromfile -i data/count.wav --ground data/count.segments -o hmmcount -mw 0.1 -ms 0.1**

and the model trained successfully. 

But when I try my own data:

**python audioAnalysis.py trainHMMsegmenter_fromfile -i data/Segmentation/10.wav --ground data/Segmentation/10.segments -o hmmcount -mw 1.0 -ms 1.0**

I get the following error:

Traceback (most recent call last):
  File "audioAnalysis.py", line 578, in <module>
    args.mtwin, args.mtstep)
  File "audioAnalysis.py", line 185, in trainHMMsegmenter_fromfile
    aS.train_hmm_from_file(wavFile, gtFile, hmmModelName, mt_win, mt_step)
  File "C:\Users\RichardHu\Anaconda3\lib\site-packages\pyAudioAnalysis\audioSegmentation.py", line 365, in train_hmm_from_file
    flags, class_names = segments_to_labels(seg_start, seg_end, seg_labs, mid_step)
  File "C:\Users\RichardHu\Anaconda3\lib\site-packages\pyAudioAnalysis\audioSegmentation.py", line 115, in segments_to_labels
    while index < end_times[-1]:
IndexError: index -1 is out of bounds for axis 0 with size 0

When I **print (seg_start, seg_end, seg_labs)** for the wav files, I get empy lists of [] [] []

Has anyone had a similar issue? Is there perhaps a specific issue with my .WAV (or .SEGMENTS file) that is causing this?

Note: I ensured that the wav file is mono and not stereo by converting it using ffmpeg. The full audio format is: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 16000 Hz, mono, s16, 256 kb/s

**Comment by 20richardh** [comment]
If the issue is the wav format, could anyone recommend audio specifics they used that worked?

**Comment by 20richardh** [comment]
It appears to be an error that arose with either my specific wav format or the way in which I used ffmpeg to process the audio data. I fixed this by using AudioSegment to process the original m4a audio files instead of ffmpeg.
