### ISSUE TITLE
Single File Regression

### ISSUE THREAD

**Issue by cozywind2010** [tyiannak/pyAudioAnalysis#298]
aT.file_regression("data/speechEmotion/01.wav",
  File "C:\Users\user\.virtualenvs\pyAudioAnalysis-kzUtWmsG\lib\site-packages\pyAudioAnalysis\audioTrainTest.py", line 1099, in file_regression
    = load_model(regression_models[0], True)
IndexError: list index out of range

I am ok training the model, however the fit part gave me error above. I used the one of the original data from the training to do the test... please help.

**Comment by cozywind2010** [comment]
I tried it again. It works when using the commanda list, but not working when using python code.

E:\xampp\htdocs\videoprocessing\pyAudioAnalysis\pyAudioAnalysis (master -> origin)
(pyAudioAnalysis-kzUtWmsG) λ python audioAnalysis.py regressionFile -i 00.wav --model svm --regression data/svmSpeechEmotion
arousal 0.600
valence -0.650

E:\xampp\htdocs\videoprocessing\pyAudioAnalysis\pyAudioAnalysis (master -> origin)
(pyAudioAnalysis-kzUtWmsG) λ python audioAnalysis.py regressionFile -i audio_full.wav --model svm --regression data/svmSpeechEmotion
arousal 0.404
valence -0.015

E:\xampp\htdocs\videoprocessing\pyAudioAnalysis\pyAudioAnalysis (master -> origin)
(pyAudioAnalysis-kzUtWmsG) λ python test.py
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    aT.file_regression("audio_full.wav",
  File "C:\Users\cozyw_cl6bnw6\.virtualenvs\pyAudioAnalysis-kzUtWmsG\lib\site-packages\pyAudioAnalysis\audioTrainTest.py", line 1109, in file_regression
    = load_model(regression_models[0], True)
IndexError: list index out of range

**Comment by cozywind2010** [comment]
Make sure to change "data/modelssvmSpeechEmotion" to "data/svmSpeechEmotion".
