### ISSUE TITLE
IndexError: index 40 is out of bounds for axis 0 with size 40

### ISSUE THREAD

**Issue by ly0303521** [tyiannak/pyAudioAnalysis#304]
`Traceback (most recent call last):
  File "myExperiment.py", line 11, in <module>
    aT.extract_features_and_train(data, 1.0, 1.0, aT.shortTermWindow, aT.shortTermStep, "svm", "svmSMtemp", False)
  File "/home/ly/Projects/pyAudioAnalysis/pyAudioAnalysis/audioTrainTest.py", line 307, in extract_features_and_train
    compute_beat=compute_beat)
  File "/home/ly/Projects/pyAudioAnalysis/pyAudioAnalysis/MidTermFeatures.py", line 245, in multiple_directory_feature_extraction
    compute_beat=compute_beat)
  File "/home/ly/Projects/pyAudioAnalysis/pyAudioAnalysis/MidTermFeatures.py", line 193, in directory_feature_extraction
    round(sampling_rate * short_step))
  File "/home/ly/Projects/pyAudioAnalysis/pyAudioAnalysis/MidTermFeatures.py", line 92, in mid_feature_extraction
    short_window, short_step)
  File "/home/ly/Projects/pyAudioAnalysis/pyAudioAnalysis/ShortTermFeatures.py", line 568, in feature_extraction
    fbank, freqs = mfcc_filter_banks(sampling_rate, num_fft)
  File "/home/ly/Projects/pyAudioAnalysis/pyAudioAnalysis/ShortTermFeatures.py", line 218, in mfcc_filter_banks
    fbank[i][rid] = rslope * (high_freqs - nfreqs[rid])
IndexError: index 40 is out of bounds for axis 0 with size 40`

**Comment by ly0303521** [comment]
anyone have ideas?
