### ISSUE TITLE
ValueError: 'diag' covars must be positive

### ISSUE THREAD

**Issue by Obile19** [tyiannak/pyAudioAnalysis#370]
Hi, When I pass `0` or bad `number of speaker` to diarization function, I have an error!
What should I do now?

**Comment by oulfik** [comment]
Have the same issue when setting numberOfSpeakers to 0 while using the command-line example in the wiki.

C:\Users\oliver\Desktop\digMed\Datenstrukturen und Analysemethoden im Gesundheitsbereich\diarization\pyaudioanalysis\pyAudioAnalysis\pyAudioAnalysis\audioSegmentation.py:326: RuntimeWarning: invalid value encountered in true_divide
  transmutation_matrix[i, :] /= transmutation_matrix[i, :].sum()
Traceback (most recent call last):
  File "C:\Users\oliver\Desktop\digMed\Datenstrukturen und Analysemethoden im Gesundheitsbereich\diarization\pyaudioanalysis\pyAudioAnalysis\pyAudioAnalysis\audioAnalysis.py", line 617, in <module>
    speakerDiarizationWrapper(args.input, args.num, args.flsd)
  File "C:\Users\oliver\Desktop\digMed\Datenstrukturen und Analysemethoden im Gesundheitsbereich\diarization\pyaudioanalysis\pyAudioAnalysis\pyAudioAnalysis\audioAnalysis.py", line 239, in speakerDiarizationWrapper
    aS.speaker_diarization(inputFile, numSpeakers, lda_dim=0, plot_res=True)
  File "C:\Users\oliver\Desktop\digMed\Datenstrukturen und Analysemethoden im Gesundheitsbereich\diarization\pyaudioanalysis\pyAudioAnalysis\pyAudioAnalysis\audioSegmentation.py", line 1005, in speaker_diarization
    hmm.means_ = means; hmm.covars_ = cov
  File "C:\Users\oliver\Desktop\digMed\Datenstrukturen und Analysemethoden im Gesundheitsbereich\diarization\pyaudioanalysis\pyAudio-env\lib\site-packages\hmmlearn\hmm.py", line 182, in covars_
    _utils._validate_covars(covars, self.covariance_type,
  File "C:\Users\oliver\Desktop\digMed\Datenstrukturen und Analysemethoden im Gesundheitsbereich\diarization\pyaudioanalysis\pyAudio-env\lib\site-packages\hmmlearn\_utils.py", line 28, in _validate_covars
    raise ValueError("'diag' covars must be positive")
ValueError: 'diag' covars must be positive
