### ISSUE TITLE
Error when using Speaker Diarization pipeline

### ISSUE THREAD

**Issue by thangld201** [tyiannak/pyAudioAnalysis#371]
When I run the following command (as illustrated in the tutorial ```!python audioAnalysis.py speakerDiarization -i ./data/diarizationExample.wav --num 2 --flsd```. I got the error <br/> 
```
Traceback (most recent call last):
  File "audioAnalysis.py", line 617, in <module>
    speakerDiarizationWrapper(args.input, args.num, args.flsd)
  File "audioAnalysis.py", line 237, in speakerDiarizationWrapper
    aS.speaker_diarization(inputFile, numSpeakers, lda_dim=5, plot_res=True)
  File "/content/pyAudioAnalysis/pyAudioAnalysis/audioSegmentation.py", line 832, in speaker_diarization
    at.load_model(os.path.join(base_dir, "svm_rbf_speaker_10"))
  File "/content/pyAudioAnalysis/pyAudioAnalysis/../pyAudioAnalysis/audioTrainTest.py", line 530, in load_model
    mean = cPickle.load(fo)
ValueError: unsupported pickle protocol: 5
```
<br/> I'm using google colaboratory environment and already installed the libraries and dependencies, what could be the cause ?

**Comment by thangld201** [comment]
@tyiannak Could you help me please ?

**Comment by thangld201** [comment]
I found where the error came from: Google Colab uses pickle 4 by default, so you have to do <br/>
```
!pip install pickle5
import pickle5 as pickle
```
