### ISSUE TITLE
ImportError: cannot import name 'available_if' from 'sklearn.utils.metaestimators'

### ISSUE THREAD

**Issue by jochou02** [tyiannak/pyAudioAnalysis#373]
Running the line `from pyAudioAnalysis import audioSegmentation as aS` gives this error in my terminal

Traceback (most recent call last):
  File "C:\Users\John\Desktop\pyAudioAnalysis\test.py", line 1, in <module>
    from pyAudioAnalysis import audioSegmentation as aS
  File "C:\Users\John\Desktop\pyAudioAnalysis\pyAudioAnalysis\audioSegmentation.py", line 19, in <module>
    import pyAudioAnalysis.audioTrainTest as at
  File "C:\Users\John\Desktop\pyAudioAnalysis\pyAudioAnalysis\audioTrainTest.py", line 2, in <module>
    from imblearn.under_sampling import RandomUnderSampler
  File "C:\Users\John\AppData\Local\Programs\Python\Python39\lib\site-packages\imblearn\__init__.py", line 53, in <module>
    from . import ensemble
  File "C:\Users\John\AppData\Local\Programs\Python\Python39\lib\site-packages\imblearn\ensemble\__init__.py", line 6, in <module>
    from ._easy_ensemble import EasyEnsembleClassifier
  File "C:\Users\John\AppData\Local\Programs\Python\Python39\lib\site-packages\imblearn\ensemble\_easy_ensemble.py", line 21, in <module>
    from ..pipeline import Pipeline
  File "C:\Users\John\AppData\Local\Programs\Python\Python39\lib\site-packages\imblearn\pipeline.py", line 18, in <module>
    from sklearn.utils.metaestimators import available_if
ImportError: cannot import name 'available_if' from 'sklearn.utils.metaestimators' (C:\Users\John\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\utils\metaestimators.py)

**Comment by ShailendraSatyarthi** [comment]
ImportError: cannot import name 'available_if' from 'sklearn.utils.metaestimators' (C:\Users\Dell\anaconda3\lib\site-packages\sklearn\utils\metaestimators.py)
