### ISSUE TITLE
problem with evaluateSegmentationClassificationDir(dirName, modelName, methodName)  from audioSegmentation.py

### ISSUE THREAD

**Issue by dagny-t** [tyiannak/pyAudioAnalysis#44]
Error in computePreRec! Confusion matrix and classNames list must be of the same size!
Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.2.3\helpers\pydev\pydevd.py", line 1580, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.2.3\helpers\pydev\pydevd.py", line 964, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "E:/int/pyAudioAnalysis-master/recognizerEmotionInVoice.py", line 76, in <module>
    testSegmentationEvaluation(select_folderEmotion,selected_types[numModel],selected_models[numModel])
  File "E:/int/pyAudioAnalysis-master/recognizerEmotionInVoice.py", line 69, in testSegmentationEvaluation
    aA.segmentationEvaluation(dirName, modelName, methodName)
  File "E:/int/pyAudioAnalysis-master\audioAnalysis.py", line 212, in segmentationEvaluation
    aS.evaluateSegmentationClassificationDir(dirName, modelName, methodName)
  File "E:/int/pyAudioAnalysis-master\audioSegmentation.py", line 580, in evaluateSegmentationClassificationDir
    [Rec, Pre, F1] = computePreRec(CM, classNames)
TypeError: 'NoneType' object is not iterable

![image](https://cloud.githubusercontent.com/assets/14835159/20032583/bf8adcc6-a395-11e6-9a33-9d21db18dd51.png)

**Comment by frisch1** [comment]
Hi Dagny - Im hitting the same error. What was the resolution to this?
