### ISSUE TITLE
IndexError: index 80 is out of bounds for size 80

### ISSUE THREAD

**Issue by guojianli** [tyiannak/pyAudioAnalysis#46]
Got below erro when run audioSegmentation.py.

`/home/gary/git/pyAudioAnalysis/audioFeatureExtraction.py:272: FutureWarning: assignment exception type will change in the future
  C[nChroma[0:I-1]] = spec
Traceback (most recent call last):
  File "/home/gary/Ide/pycharm-community-5.0.4/helpers/pydev/pydevd.py", line 2411, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/gary/Ide/pycharm-community-5.0.4/helpers/pydev/pydevd.py", line 1802, in run
    launch(file, globals, locals)  # execute the script
  File "/home/gary/git/pyAudioAnalysis/test.py", line 4, in <module>
    segments = aS.silenceRemoval(x, Fs, 0.020, 0.020, smoothWindow = 1.0, Weight = 0.3, plot = True)
  File "/home/gary/git/pyAudioAnalysis/audioSegmentation.py", line 613, in silenceRemoval
    ShortTermFeatures = aF.stFeatureExtraction(x, Fs, stWin * Fs, stStep * Fs)        # extract short-term features
  File "/home/gary/git/pyAudioAnalysis/audioFeatureExtraction.py", line 579, in stFeatureExtraction
    chromaNames, chromaF = stChromaFeatures(X, Fs, nChroma, nFreqsPerChroma)
  File "/home/gary/git/pyAudioAnalysis/audioFeatureExtraction.py", line 272, in stChromaFeatures
    C[nChroma[0:I-1]] = spec            
IndexError: index 80 is out of bounds for size 80`

**Comment by LusciousPear** [comment]
I got this as well.  +1

**Comment by guojianli** [comment]
fixed on this pull request. https://github.com/tyiannak/pyAudioAnalysis/pull/47
