### ISSUE TITLE
Error on using audioTrainTest, audioBasicIO, and Utilities... 

### ISSUE THREAD

**Issue by Kamatio** [tyiannak/pyAudioAnalysis#49]
Dear Fellows, I am trying to run pyAudio Analysis on windows, I can run many library functions without errors but some have failed to run and tried to search in all related areas of solution can't get solution.
Errors: Can't **import audioTrainTest as aT** on Python Jupyter and even on window command function the error says **Traceback (most recent call last):
File "", line 1, in 
ImportError: No module named 'audioTrainTest** and when I tried to install it through pip install it shows me **Could not find a version that satisfies the requirement audioTrainTest (from versions: )
No matching distribution found for utilities**. This error goes to **audioBasicIO** and **Utilities** as well.

I would appreciate your help to correct these errors, I am using windows 10. Anaconda Python 3.5...
Thanks a lot.
Blessings to you all.....

**Comment by sreejasuresh007** [comment]
I am getting this error. Kindly help. 

Traceback (most recent call last):
  File "E:\dATAbnc\pyAudioAnalysis-master\demo.py", line 7, in <module>
    F = audioFeatureExtraction.stFeatureExtraction(x, Fs, 0.050*Fs, 0.025*Fs);
  File "E:/dATAbnc/pyAudioAnalysis-master/audioFeatureExtraction.py", line 563, in stFeatureExtraction
    x = signal[curPos:curPos+Win]                    # get current window
IndexError: invalid index to scalar variable.
>>>

**Comment by The-Gupta** [comment]
[Here](https://github.com/tyiannak/pyAudioAnalysis/issues/7), the author [Theodoros Giannakopoulos](https://github.com/tyiannak) comments - 

> **Hi. The whole library has only been tested in Python 2.7**

**Comment by XiaoyaLiao** [comment]
You can use Linux and Python 2.7 if it is possible for you. Then everything goes well. Else maybe you have to change your environment and platform, virtual box for example. As far as I know...

**Comment by thaingiW** [comment]
In Emotion recognition from speech this error appears.Please help to solve.
Loading data from berlin dataset...
Error in readAudioFile(): Unknown file type!
Traceback (most recent call last):
  File "/home/lwin/Emotion-Recognition-from-Speech-master/src/emorecognition.py", line 41, in <module>
    db = Dataset(path,db_type,decode=False)
  File "/home/lwin/Emotion-Recognition-from-Speech-master/src/dataset.py", line 18, in __init__
    self.get_berlin_dataset(path)
  File "/home/lwin/Emotion-Recognition-from-Speech-master/src/dataset.py", line 35, in get_berlin_dataset
    self.targets.append(classes[audio[5]])
IndexError: string index out of range

**Comment by Sowhardhhonnappa** [comment]
ModuleNotFoundError: No module named 'audioTrainTest'

Same error

**Comment by charx0r** [comment]
The python3 version has a new function name `extract_features_and_train ` which works.
