### ISSUE TITLE
Problem with featureAndTrain

### ISSUE THREAD

**Issue by tdurlatka** [tyiannak/pyAudioAnalysis#59]
Hello.
I have a problem. When I try create a new model using featureAndTrain I get an error:
line 199, in featureAndTrain
numOfFeatures = features[0].shape[1] 
IndexError: tuple index out of range
I have no idea what I'm doing wrong. Please, help!

**Comment by AhmedHamedTN** [comment]
Did you try to check whether one of the sound files is empty ?

**Comment by tdurlatka** [comment]
None is empty.

**Comment by arunbahl** [comment]
I'm seeing the same error - features[0].shape looks like (68,) in my case.

**Comment by tdurlatka** [comment]
Problem solved - each directory must contain more than one WAV file.

**Comment by arunbahl** [comment]
Thanks!

**Comment by simotonno** [comment]
Dear all,
I have a similar problem. The model train good but, when i try to estimate the regression for data stored in a folder the function return this error message:  [_, _, _, mtWin, mtStep, stWin, stStep, computeBEAT] = loadSVModel(regressionModels[0], True)
IndexError: list index out of range

Seems that it can not load the model.. Can you help me?

**Comment by sreejasuresh007** [comment]
Traceback (most recent call last):
  File "E:\dATAbnc\pyAudioAnalysis-master\pyAudioAnalysis-master\demo.py", line 7, in <module>
    F = audioFeatureExtraction.stFeatureExtraction(x, Fs, 0.050*Fs, 0.025*Fs);
  File "E:\dATAbnc\pyAudioAnalysis-master\pyAudioAnalysis-master\audioFeatureExtraction.py", line 544, in stFeatureExtraction
    N = len(signal)                                # total number of samples
TypeError: object of type 'numpy.float64' has no len()

**Comment by arunimamookherjee** [comment]
I got the same error. Check the arousal.csv and valence.csv . The error will be gone when there's data in them.

**Comment by ScreamShiv** [comment]
@simotonno did u get the solution?? please tell.
