### ISSUE TITLE
Error in stFeatureExtraction

### ISSUE THREAD

**Issue by sreejasuresh007** [tyiannak/pyAudioAnalysis#63]
Please help. 

Traceback (most recent call last):
  File "E:\dATAbnc\pyAudioAnalysis-master\pyAudioAnalysis-master\demo.py", line 7, in <module>
    F = audioFeatureExtraction.stFeatureExtraction(x, Fs, 0.050*Fs, 0.025*Fs);
  File "E:\dATAbnc\pyAudioAnalysis-master\pyAudioAnalysis-master\audioFeatureExtraction.py", line 544, in stFeatureExtraction
    N = len(signal)                                # total number of samples
TypeError: object of type 'numpy.float64' has no len()

**Comment by tuulihill** [comment]
I've been getting this error too. I tried to change the type of signal but didn't manage too.

**Comment by sreejasuresh007** [comment]
Actually my issue got solved when I changed the input file. Now its working fine.

**Comment by onsunsl** [comment]
I've been getting this error too

**Comment by tuulihill** [comment]
I also got past this with another input file.

**Comment by tyiannak** [comment]
@tuulihill could you share an input file to check it, because I am pretty sure this error occurs when audioBasicIO cannot read the input file

**Comment by tuulihill** [comment]
@tyiannak I was just testing it out using the threewords.wav file that came with, then I switched to count.wav. Then in audioBasicIO.py I had to change xrange to range

**Comment by ziweizh** [comment]
I also encountered the same error which persisted despite changing 'xrange' to 'range'. What's the solution?

**Comment by manish-manghwani** [comment]
I have encountered the same issue.  on changing the audio file, it worked for me. Details for admissible file  format is as follows :  
File size : 187.9KB
codec : wav
sample rate : 16000 Hz.


The one which is not running is with 
File size : > 2MB
codec : opus
sample rate : 48000 Hz 


The above information is my observation, it may or may not be relevant.
