### ISSUE TITLE
I tried running under python3, but there was a problem

### ISSUE THREAD

**Issue by onsunsl** [tyiannak/pyAudioAnalysis#67]
I modified the code, in python3 can analyze the data directory wav file, but replaced by their own recorded wav file out of some problems.

aS.trainHMM_fromFile('data1/tts.wav', 'data1/tts.segments', 'tts', 0.05, 0.05) # train using a single file
flagsInd, classNamesGT, acc, CM = aS.hmmSegmentation('./data1/tts.wav', 'tts', True, './data1/tts.segments')        

the tts.sements file:
0.0000, 0.1978,亲
0.1978, 0.3956,爱
0.3956, 0.5933,的
0.5933, 1.2171,
1.2171, 1.4149, 你
1.4149, 1.6126, 好
1.6126, 1.8104, 吗
1.8104, 2.0081, 你
2.0081, 2.2059, 来
2.2059, 2.4037, 自
2.4037, 2.6015, 哪
2.6015, 2.7992, 里
2.7992, 2.9970, ？
2.9970, 3.1600, ？

Traceback (most recent call last):
  File "D:/AnyCode/python/Robot3D/pyAudioAnalysis-master/demoTest.py", line 53, in <module>
    flagsInd, classNamesGT, acc, CM = aS.hmmSegmentation('./data1/tts.wav', 'tts', True, './data1/tts.segments')             # test 1
  File "D:\AnyCode\python\Robot3D\pyAudioAnalysis-master\audioSegmentation.py", line 447, in hmmSegmentation
    flagsInd = hmm.predict(Features.T)                            # apply model
  File "C:\Anaconda3\lib\site-packages\hmmlearn\base.py", line 334, in predict
    _, state_sequence = self.decode(X, lengths)
  File "C:\Anaconda3\lib\site-packages\hmmlearn\base.py", line 294, in decode
    self._check()
  File "C:\Anaconda3\lib\site-packages\hmmlearn\hmm.py", line 175, in _check
    self.n_components)
  File "C:\Anaconda3\lib\site-packages\sklearn\mixture\gmm.py", line 761, in _validate_covars
    raise ValueError("'diag' covars must be non-negative")
ValueError: 'diag' covars must be non-negative

Hope to provide python3 version, thank you

**Comment by philipperemy** [comment]
Python3 is not yet supported.

**Comment by phliulei** [comment]
Have you solve that? the same problem. @onsunsl

**Comment by philipperemy** [comment]
@shubham99bisht won't be enough. It's more complex than that

**Comment by tyiannak** [comment]
I will be pushing a python3 compatible version soon
