### ISSUE TITLE
Issue while running sample example

### ISSUE THREAD

**Issue by peps0791** [tyiannak/pyAudioAnalysis#81]
I am running the sample code from the wiki:

`from pyAudioAnalysis import audioBasicIO
from pyAudioAnalysis import audioFeatureExtraction
import matplotlib.pyplot as plt
[Fs, x] = audioBasicIO.readAudioFile("sample.wav");
F = audioFeatureExtraction.stFeatureExtraction(x, Fs, 0.050*Fs, 0.025*Fs);
plt.subplot(2,1,1); plt.plot(F[0,:]); plt.xlabel('Frame no'); plt.ylabel('ZCR'); 
plt.subplot(2,1,2); plt.plot(F[1,:]); plt.xlabel('Frame no'); plt.ylabel('Energy'); plt.show()`

I get the following error:

Traceback (most recent call last):
  File "sample.py", line 5, in <module>
    F = audioFeatureExtraction.stFeatureExtraction(x, Fs, 0.050*Fs, 0.025*Fs);
  File "/home/peps/Music_Recognition-ML/pyAudioAnalysis/audioFeatureExtraction.py", line 580, in stFeatureExtraction
    curFV[2] = stEnergyEntropy(x)                    # short-term entropy of energy
  File "/home/peps/Music_Recognition-ML/pyAudioAnalysis/audioFeatureExtraction.py", line 56, in stEnergyEntropy
    subWindows = frame.reshape(subWinLength, numOfShortBlocks, order='F').copy()
ValueError: total size of new array must be unchanged

on inserting some print statements i get:

frame length--> 2205
frame shape--> (2205, 2)
Eol--> 31.9334385705
L--> 2205
subWinLength--> 220

frame length--> 2200
frame shape--> (2200, 2)

Any ideas what am I doing wrong ?

**Comment by yuliji-seedlink** [comment]
I converted the WAV files to a sample rate of 16000, and then it worked.
